controller:
  config:
    entries:
      external-status-address: "127.0.0.1"
  nginxplus: false
  service:
    type: NodePort
    externalTrafficPolicy: Cluster
    httpPort:
      nodePort: 30080
  ingressClass:
    name: nginx
