apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lab
  namespace: argocd
spec:
  sourceRepos:
    - git://lab-git.argocd.svc.cluster.local/repo.git
  destinations:
    - namespace: gitops-lab
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
